name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install .

      - name: Set PYTHONPATH
        run: |
          echo "PYTHONPATH=$(pwd)/mpmetrics/src/mpmetrics" >> $GITHUB_ENV


      - name: Run tests
        env:
          MPLBACKEND: Agg
          PYTHONPATH: src
        run: pytest -q
